name: SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu' # Alternative distribution options are available
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build project
        run: ./gradlew build assemble assembleAndroidTest
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{secrets.KEY}}
          known_hosts: unnecessary
      - name: Adding known hosts
        run: ssh-keyscan -p ${{secrets.PORT}} -H ${{secrets.HOST}} >> ~/.ssh/known_hosts
      - name: Send to remote apks server
        run: |
          scp -P ${{secrets.PORT}} app/build/outputs/apk/debug/app-debug.apk ${{secrets.USERNAME}}@${{secrets.HOST}}:/home/pedro/marathon
          scp -P ${{secrets.PORT}} app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk ${{secrets.USERNAME}}@${{secrets.HOST}}:/home/pedro/marathon
      - name: Executing Marathon
        run: |
            ssh -p ${{secrets.PORT}} ${{secrets.USERNAME}}@${{secrets.HOST}} 
            adb devices
            cd /home/pedro/marathon
            marathon
      - name: Copying JaCoCo files to Runner
        run: |
          scp -P ${{secrets.PORT}} -r ${{secrets.USERNAME}}@${{secrets.HOST}}:/home/pedro/marathon/reports/device-files/ .
          cd device-files
          ls -l
      # - name: Sonar Analysis
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   run: ./gradlew jacocoTestReport sonarqube
