name: SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud-analysis:
    name: SonarCloud analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x ./gradlew

    - name: Run tests and generate Jacoco report
      run: ./gradlew jacocoTestReport

    - name: Upload Jacoco report to SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      with:
        organization: "imphk"
        project: "imphk_Identifier"
        token: ${{ secrets.SONAR_TOKEN }}
